doi_crossref_api_endpoint: 'https://test.crossref.org/servlet/deposit'
doi_crossref_prefix: 10.33009/
doi_crossref_suffix_source: timerand
doi_crossref_username: crossref_username
doi_crossref_password: crossref_password
_core:
  default_config_hash: NY5ChiN89AStyt0-IPAiS6aTLnUEl3C2mAXrvF4ADOs
doi_crossref_suffix_prefix: ldbase.
