_core:
  default_config_hash: YGueb7ImKHSG1RRmIB1iqPHVGXTmI2yvCcB-RX7FPeY
site_id: '1'
url_http: 'http://localhost:9999/matomo/'
url_https: ''
domain_mode: 0
visibility:
  request_path_mode: 0
  request_path_pages: "/admin\r\n/admin/*\r\n/batch"
  user_role_mode: 1
  user_role_roles: {  }
  user_account_mode: 1
track:
  mailto: true
  files: true
  files_extensions: '7z|aac|arc|arj|asf|asx|avi|bin|csv|dat|do|doc(x|m)?|dot(x|m)?|dta|exe|flv|gif|gz|gzip|hqx|inp|jar|jnp|jpe?g|js|json|m|mat|mp(2|3|4|e?g)|mov(ie)?|msi|msp|mtj|mtw|out|pdf|phps|png|ppt(x|m)?|pot(x|m)?|pps(x|m)?|ppam|py|pzf|pzfx|sld(x|m)?|thmx|qtm?|r|ra(m|r)?|rda|rdata|rmd|sas|sas7bdat|sav|sea|sit|sps|tar|tgz|torrent|txt|wav|wma|wmv|wpd|xls(x|m|b)?|xlt(x|m)|xlam|xml|z|zip'
  colorbox: true
  userid: false
  messages: {  }
  site_search: false
privacy:
  donottrack: true
  disablecookies: false
custom:
  variable:
    1:
      slot: 1
      name: ''
      value: ''
      scope: visit
    2:
      slot: 2
      name: ''
      value: ''
      scope: visit
    3:
      slot: 3
      name: ''
      value: ''
      scope: visit
    4:
      slot: 4
      name: ''
      value: ''
      scope: visit
    5:
      slot: 5
      name: ''
      value: ''
      scope: visit
codesnippet:
  before: "document.addEventListener('DOMContentLoaded', function(){ \r\n  \r\n  var consentGiven = 0;\r\n  var cookieArray = document.cookie.split(\";\"); \r\n  \r\n  for(var i=0; i < cookieArray.length; i++) {\r\n    var cookiePair = cookieArray[i].split(\"=\");\r\n    \r\n    if('cookie-agreed' == cookiePair[0].trim()) {\r\n    \r\n      if(cookiePair[1].trim() == 2) {\r\n        consentGiven = 1;\r\n      }\r\n    }\r\n  }   \r\n \r\n  if (!consentGiven) {\r\n      _paq.push(['requireConsent']);\r\n      _paq.push(['disableCookies']);\r\n    }\r\n \r\n    if (consentGiven) {\r\n      _paq.push(['setConsentGiven']);\r\n    }\r\n\r\n}, false);"
  after: ''
translation_set: false
disable_tracking: false
cache: true
page_title_hierarchy: false
page_title_hierarchy_exclude_home: true
status_codes_disabled: {  }
