_core:
  default_config_hash: ByOVf1cU9r5NkZ4ieBJ7k9sUid6jb03ojMN1gjJ0-OU
site_key: 6LfhtG0pAAAAAJI939BN517EW6e8SarBaQp68nTf
secret_key: 6LfhtG0pAAAAAB9IJQYZYQEHZ5zrHYBHmjdCCYss
verify_hostname: true
use_globally: false
widget:
  theme: light
  type: image
  size: ''
  noscript: false
