_core:
  default_config_hash: ae8AQLsAFXvfcLPmE4YUBcxThAqf7psqRTHzhccslls
langcode: en
site_key: ''
secret_key: ''
hide_badge: false
verify_hostname: true
default_challenge: recaptcha/reCAPTCHA
error_message: 'Antibot verification failed.'
cacheable: false
library_use_recaptcha_net: false
