_core:
  default_config_hash: ae8AQLsAFXvfcLPmE4YUBcxThAqf7psqRTHzhccslls
site_key: 6Lekq20pAAAAAH-Gj7PdImnUMgzXCi4i9tHYNU9d
secret_key: 6Lekq20pAAAAAGyzPNfK7HPkiMP1wEqGe-d2WO-N
hide_badge: false
verify_hostname: false
default_challenge: image_captcha/Image
error_message: 'Antibot verification failed.'
cacheable: false
library_use_recaptcha_net: false
