_core:
  default_config_hash: FS38f8_G3S09nKLtUCOEs0IhkjQQRl3UfDJnFD7B1qY
credentials_file: ''
bucket: ''
region: us-east-1
use_cname: false
use_customhost: false
hostname: ''
domain: ''
use_path_style_endpoint: false
cache_control_header: ''
encryption: ''
use_https: false
ignore_cache: false
redirect_styles_ttl: 0
root_folder: ''
public_folder: public
private_folder: private
presigned_urls: ''
saveas: ''
torrents: ''
access_key: ''
secret_key: ''
use_instance_profile: false
no_rewrite_cssjs: false
