_core:
  default_config_hash: ayuIhHBn6wN-ozw7Zy0WDYYlp-WDBq0RxDXi6o8V27I
custom_descriptions:
  itemListElement: null
  mainEntity: null
  mainEntityOfPage: null
  subtype: 'A more specific subtype for the item. This is used to allow more specificity without having to create dedicated Schema.org entity types.'
  layoutParagraphs: 'A layout built using paragraphs. Layout paragraphs allows site builders to construct a multi-column landing page using Schema.org related paragraphs types.'
  3DModel: 'A 3D model represents some kind of 3D content'
  Blog: 'A blog, sometimes known as a "weblog".'
  Campground: 'A camping site, campsite, or campground is a place used for overnight stay in the outdoors.'
  CampingPitch: 'A camping pitch is an individual place for overnight stay in the outdoors, typically being part of a larger camping site, or campground.'
  CollectionPage: 'A collection page.'
  EventSeries: 'A series of events.'
  FAQPage: 'A page presenting one or more "Frequently asked questions".'
  Guide: 'A guide is a page or article that recommends specific products or services, or aspects of a thing for a user to consider.'
  HealthTopicContent: 'A web page about some aspect of a health topic, e.g. a condition, its symptoms or treatments.'
  ImageGallery: 'An image gallery page.'
  ItemList: 'A list of items of any sort.'
  Language: 'Natural languages such as Spanish, Tamil, Hindi, English, etc.'
  LibrarySystem: 'A collaborative system amongst several libraries.'
  LodgingReservation: 'A reservation for lodging at a hotel, motel, inn, etc.'
  MediaGallery: 'A mixed-media page that can contain media such as images, videos, and other multimedia.'
  MenuItem--offers: 'The offer price of a product, or of a price component when attached to PriceSpecification and its subtypes.'
  ProductGroup: 'A product group represents a group of products that vary only in certain well-described ways, such as by size, color, material etc.'
  RealEstateListing: 'A listing that describes one or more real-estate offers.'
  Recommendation: 'A type of Review that suggests or proposes something as the best option or best course of action.'
  SatiricalArticle: 'An Article whose content is primarily satirical in nature, i.e. unlikely to be literally true.'
  Schedule: 'A schedule defines a repeating time period used to describe a regularly occurring event.'
  SpecialAnnouncement--category: 'A category for the item. It is important to provide a value for "category" where possible, most ideally as a well known URL from Wikipedia or Wikidata. In the case of the 2019-2020 Coronavirus pandemic, this should be "https://en.wikipedia.org/w/index.php?title=2019-20_coronavirus_pandemic" or "https://www.wikidata.org/wiki/Q81068910".'
  Statement: 'A statement about something.'
  Syllabus: 'A syllabus that describes the material covered in a course'
  UserReview: 'A review created by an end-user (e.g. consumer, purchaser, attendee etc.).'
  VideoGallery: 'A video gallery page.'
  WebContent: 'Web Content is a type representing all Web Page, Web Site and Web Page Element content.'
  abstract: 'An abstract is a short description that summarizes a Creative Work.'
  backstory: 'Provides a textual summary giving a brief explanation of why and how an article was created.'
  cookTime: 'The time it takes to actually cook the dish.'
  duration: 'The duration of the item (movie, audio recording, event, etc.).'
  endDate: 'The end date and time of the item.'
  exceptDate: 'Defines a date/time during which a scheduled event will not take place.'
  floorLevel: 'The floor level for an accommodation in a multi-storey building.'
  gender: 'Gender of something.'
  hasHealthAspect: 'Indicates the aspect or aspects specifically addressed in some health topic content.'
  knowsLanguage: 'Indicates a known language.'
  parentOrganization: 'The larger organization that this organization is a sub organization of.'
  performTime: 'The length of time it takes to perform instructions or a direction (not including time to prepare the supplies).'
  prepTime: 'The length of time it takes to prepare the items to be used in instructions or a direction.'
  recipeInstruction: 'A step in making the recipe, in the form of a single item (document, video, etc.).'
  size: "A standardized size of a product or creative work, specified either through a simple textual string (for example 'XL', '32Wx34L'), a QuantitativeValue with a unitCode, or a comprehensive and structured size specification."
  startDate: 'The start date and time of the item.'
  study: 'The status of the study.'
  subTrip: 'Identifies a trip that is a subTrip of this trip.'
  totalTime: 'The total time required to perform instructions or a direction (including time to prepare the supplies).'
  yearBuilt: 'The year an accommodation was constructed.'
help_descriptions: true
