_core:
  default_config_hash: Ot4pEuzVAMe0ZpSf3H6_kWEcGCtybc2TB_-hEXx4hr8
schema_property_order:
  - url
  - identifier
  - inDefinedTermSet
  - inLanguage
  - name
  - alternateName
  - headline
  - alternativeHeadline
  - givenName
  - additionalName
  - familyName
  - description
  - disambiguatingDescription
  - articleBody
  - text
  - author
  - image
  - photo
  - primaryImageOfPage
  - video
  - thumbnail
  - thumbnailUrl
  - contentUrl
  - address
  - addressCountry
  - addressRegion
  - addressLocality
  - postalCode
  - postOfficeBoxNumber
  - streetAddress
  - streetAddress
  - contactPoint
  - telephone
  - fax
  - email
  - startDate
  - endDate
  - duration
schema_property_image_styles:
  image: large
  thumbnail: thumbnail
schema_type_entity_references_display:
  block_content: entity
  paragraph--layout: none
  paragraph: entity
  media: entity
  Intangible: entity
  node--Thing: url
entity_types_exclude_url:
  - block_content
  - media
  - paragraph
