_core:
  default_config_hash: QboURfwbKzS6Q3kLb1ydmpqj31z_-2vc-dKvsP99Gig
paragraphs_library:
  - ContactPoint
  - MedicalAudience
  - MedicalContraindication
  - MedicalIndication
  - MedicalCause
  - MedicalProcedure
  - MedicalRiskFactor
  - MedicalTherapy
  - MedicalSignOrSymptom
  - Statement
  - Quotation
  - CollectionPage
  - ItemList
  - MediaGallery
  - ImageGallery
  - VideoGallery
schema_property_access:
  Person--ContactPoint:
    - contactType
    - telephone
