login:
  authenticated:
    redirect_url: /user
    weight: '-10'
  content_administrator:
    redirect_url: ''
    weight: '-10'
  administrator:
    redirect_url: ''
    weight: '-10'
  fcrr_admin:
    redirect_url: ''
    weight: '-10'
logout:
  authenticated:
    redirect_url: /home
    weight: '-10'
  content_administrator:
    redirect_url: ''
    weight: '-10'
  administrator:
    redirect_url: ''
    weight: '-10'
  fcrr_admin:
    redirect_url: ''
    weight: '-10'
